baseURL = "https://manucalop.github.io/sciencebricks/"
languageCode = "en-us"
title = 'Science Bricks'
theme = "hugo-theme-m10c"

[params]
  author = "Manuel Castillo-Lopez"
  description = "Learn Science. One Brick at a Time."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/manucalop"
